### PR TITLE
DEP PHP Support in CMS5

### PR DESCRIPTION
**Pull request by sabina-talipova**
## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10402

### CODE REVIEW

**Comment by sabina-talipova** [comment]
Requires 
- https://github.com/silverstripe/silverstripe-mfa/pull/476

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Fails with "Registration failed: decodeNoPadding() doesn't tolerate padding" when I manually test with a yubikey

Exception comes from vendor/paragonie/contant_time_encoding/src/Base32.php

**Comment by GuySartorelli** [comment]
That class has `decodeNoPadding()` and `decode()` (the latter of which _does_ tolerate padding).
It seems like it's common to use `str_pad()` or similar to add padding to encoded strings... if you can include the full stack trace there I might be able to see where that padding's being added and whether we can either not include the padding, or use the other decode method.

Relevant: https://github.com/paragonie/constant_time_encoding/releases/tag/v2.6.0

**Review by emteknetnz — APPROVED** [review]
We'll merge as is and fix issue post-beta - https://github.com/silverstripe/silverstripe-webauthn-authenticator/issues/124

**Pull request merged**
